version: "2"
services:
  loadbalancer:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  app:
    #image: apprecious
    # In version 2, build can specify a build context and an alternate Dockerfile
    build:
      context: .
      dockerfile: ops/Dockerfile.apprecious
    depends_on: 
      - redis
    links:
      - redis
    ports:
      - 4567
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VIRTUAL_HOST=apprecious.local
  
  redis:
    image: redis:3.0
    ports:
      - 6379
